# Generated by Django 5.1.1 on 2024-10-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
