# Generated by Django 5.1.1 on 2024-09-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventoTipo', models.CharField(choices=[('ensayo', 'Ensayo'), ('grabacion', 'Grabacion'), ('show', 'Show'), ('otro', 'Otro')], default='otro', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioLlegada', models.DateField(blank=True, null=True)),
                ('horarioPruebaSonido', models.DateField(blank=True, null=True)),
                ('horarioTocar', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalidadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=35)),
                ('ciudad', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='VestimentaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vestimenta', models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal'), ('disfraz', 'Disfraz'), ('libre', 'Libre')], default='libre', max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='dineroCobrar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventoApp.eventotipomodel'),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventoApp.horariomodel'),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventoApp.localidadmodel'),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='vestimenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventoApp.vestimentamodel'),
        ),
    ]
