# Generated by Django 5.1.1 on 2024-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('listaCanciones', models.TextField()),
                ('foto_grupo', models.ImageField(blank=True, null=True, upload_to='grupos/')),
                ('usuarios', models.ManyToManyField(related_name='grupos', to='usuario.usuario')),
            ],
        ),
    ]
