# Generated by Django 5.1.1 on 2024-11-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_alter_grupo_listacanciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='foto_grupo',
        ),
    ]
