# Generated by Django 5.1.1 on 2024-11-07 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0003_remove_grupo_foto_grupo'),
        ('usuario', '0002_alter_usuario_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='grupo',
            name='userDueño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuario.usuario'),
        ),
    ]
