# Generated by Django 5.2.8 on 2026-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0006_alter_grupo_userdueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
