# Generated by Django 5.1.1 on 2024-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=20)),
                ('roll', models.CharField(max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
            ],
        ),
    ]
