# Generated by Django 5.1.1 on 2024-11-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='roll',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('invitado', 'Invitado')], default='invitado', max_length=20, null=True),
        ),
    ]
