# Generated by Django 5.1.1 on 2024-11-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0006_alter_grupo_userdueño'),
        ('usuario', '0002_alter_usuario_roll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
