# Generated by Django 5.1.1 on 2024-11-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_horario_horariollegada_and_more'),
        ('grupo', '0005_alter_grupo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='grupo.grupo'),
            preserve_default=False,
        ),
    ]
