# Generated by Django 5.1.1 on 2024-09-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('partitura', models.FileField(upload_to='partituras/')),
                ('fechaCarga', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='grupoApp.grupomodel')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMultimedia', models.CharField(max_length=20)),
                ('archivo', models.FileField(upload_to='')),
                ('fechaSubida', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='carpetaApp.carpetamodel')),
            ],
        ),
    ]
